### ISSUE TITLE
Create settings page

### ISSUE THREAD

**Issue by kochol** [kochol/Capitan#20]
- [x] Create settings page
 - [x] Change graphics quality
- [x] Save the settings

# Resources

0=low 1=Mid 2=High 3=Epic

https://docs.unrealengine.com/latest/INT/Engine/Performance/Scalability/ScalabilityReference/index.html#postprocessing-sgstoppostprocessquality
![](https://answers.unrealengine.com/storage/temp/38733-executeconsolecommand.png)

**Comment by amirahmad** [comment]
create Time GUI when game is paused.

**Comment by kochol** [comment]
This must be in another task

**Comment by amirahmad** [comment]
create sound setting
