### ISSUE TITLE
create tutorial

### ISSUE THREAD

**Issue by amirahmad** [kochol/Capitan#27]
Tutorial for campaign.

**Comment by kochol** [comment]
Tutorial tasks.
- [ ] Welcome, Captain. Destroy the drones to complete your training. Continue button.
- [ ] Touch and slide orange circle to change the path of your airplane. Aim for the first enemy.
- [ ] Touch the Play button to move your plane forward. Planes shoot automatically.
- [ ] Great job! This is a turn based game. All aircraft move at the same time, after planning is done. Continue button.
- [ ] Touch the SuperSpeed power-up button to catch up to the next plane.
- [ ] Touch and slide to scroll the map. Pinch to zoom. Continue button.
- [ ] Wait for player to kill all drones.
