### ISSUE TITLE
some bugs in syncing

### ISSUE THREAD

**Issue by amirahmad** [kochol/Capitan#28]
![324](https://cloud.githubusercontent.com/assets/2282796/9802133/44a047da-582d-11e5-8190-9f404ee3e7ed.PNG)

**Comment by amirahmad** [comment]
the above picture is simple, but there is another bug some thing like don't shooting bullet and airplane's rotation 90 degree in that location

**Comment by kochol** [comment]
Maybe your internet disconnects for one round.
