### ISSUE TITLE
Scale dragable depend on zoom

### ISSUE THREAD

**Issue by kochol** [kochol/Capitan#4]
Scale dragable depend on zoom so players on mobile can easily drag it.

**Comment by kochol** [comment]
You are scaling the actor you must only scale the static mesh.

**Comment by amirahmad** [comment]
fixed scaling static mesh instead of scaling the actor component.

**Comment by kochol** [comment]
Issue moved to [kochol/SkyHeroes #4](https://github.com/kochol/SkyHeroes/issues/4) via [**ZenHub**](https://www.zenhub.com/)
