### ISSUE TITLE
Smooth Movement for Camera

### ISSUE THREAD

**Issue by amirahmad** [kochol/Capitan#57]

**Comment by kochol** [comment]
امیر احمد از این دوربینی که نوشتی راضی نیستم اصلا

**Comment by kochol** [comment]
@kochol 5 ثانیه طول می کشه تا بیاد سر جاش چه خبره 
بعد هم کدت صد در صد به نظرم اشتباه است.

**Comment by kochol** [comment]
@kochol بعد هم باید از Lerp استفاده کنی تایم لاینت هم از 0 بره تا 1 مثلا تو 0.5 ثانیه
