### ISSUE TITLE
Add health to planes.

### ISSUE THREAD

**Issue by kochol** [kochol/Capitan#6]
I think we can't use unreal engine damage system because of our networking system.

**Comment by kochol** [comment]
امیر این تسک ربطی به جی یو ای نداره فقط می خوام یه چندتا پارامتر به کلاس هواپیما اضافه بشه

**Comment by kochol** [comment]
health and max health

**Comment by kochol** [comment]
add max health too.

**Comment by amirahmad** [comment]
added max health
