### ISSUE TITLE
Disable powerup buttons when game is running

### ISSUE THREAD

**Issue by kochol** [kochol/Capitan#60]
Disable powerup buttons when game is running and enable them after server update.

**Comment by amirahmad** [comment]
Done.

**Comment by kochol** [comment]
کد این کجاست؟

**Comment by amirahmad** [comment]
![disable](https://cloud.githubusercontent.com/assets/2282796/13277992/fe043ef2-dae1-11e5-9cd9-37d379bf2145.PNG)
