### ISSUE TITLE
Buy powerups in the middle of game.

### ISSUE THREAD

**Issue by amirahmad** [kochol/Capitan#78]
وقتی داری با هوش مصنوعی بازی میکنی اگه دور 180 نداشته باشی, بازی میره رو مخ :D

**Comment by kochol** [comment]
خوب چی کارش کنیم؟

**Comment by amirahmad** [comment]
heyyy dore hamdige micharkhim ba AI badesham player khaste mishe bega mire :D . migam badaz chanta dor behavior esh avaz beshe ye taraf dg dor bezane o ina ...

**Comment by kochol** [comment]
من میگم که وسط بازی بتونه خرید کنه

**Comment by kochol** [comment]
نظرت جیه؟

**Comment by amirahmad** [comment]
اگر وسط بازی خرید کنه یکم گیم پلی تغییر میکنه میخوای بزاریم ببینیم چطور میشه؟

**Comment by kochol** [comment]
چند نفر گفتن که حاضرن وسط بازی دو برابر پول بدن و پاور آپ بخرن.
دیدی تو پینت بال یارو جو گیر می شه و هی تیر می خره ماهم باید یه چنین شرایطی رو بوجود بیاریم که اگه کل کل شد وسط بازی هم بشه خرید زد.

**Comment by amirahmad** [comment]
vaghti powerup e player tamom mishe button e buy powerup on bala rangi she ke player kharid kone, vaghean tasir dare :D
